- name: Install MySql Server
  ansible.builtin.package:
    name: mysql-server
    state: installed

- name: enable and start service   
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: connect to mysql
  community.mysql.mysql_info:
  login_user: "{{user}}"
  login_password: "{{password}}"
  login_host: "{{host}}"
  register: mysql_info
  ignore_errors: true

- name: print
  ansible.builtin.debug:
  msg: "{{ mysql_info }}"   
      

- name: Install PyMySql and cryptography
  ansible.builtin.pip:
    name: "{{item}}"
    executable: pip3.9
  loop:
  - cryptography
  - PyMySql   

- name: set root password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{password}}"
  when: mysql_info.failed is true  
